# Site settings
title: blog.miguel.im
email: miguelbeltransanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write, sometimes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.miguel.im" # the base hostname & protocol for your site
twitter_username: miguelb93
github_username:  MiguelBel

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
