version: '3.4'
services:
  app:
    build:
      context: .
    working_dir: /opt/app
    volumes:
      - '.:/opt/app'
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: jekyll serve -H 0.0.0.0